/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personagem;

/**
 *
 * @author Arthur
 */
public class EscolheHorario extends javax.swing.JFrame {

    /**
     * Creates new form EscolheHorario
     */
    public EscolheHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        domNoite = new javax.swing.JCheckBox();
        domTarde = new javax.swing.JCheckBox();
        domManha = new javax.swing.JCheckBox();
        segManha = new javax.swing.JCheckBox();
        segNoite = new javax.swing.JCheckBox();
        segTarde = new javax.swing.JCheckBox();
        terManha = new javax.swing.JCheckBox();
        terNoite = new javax.swing.JCheckBox();
        terTarde = new javax.swing.JCheckBox();
        quaManha = new javax.swing.JCheckBox();
        quaNoite = new javax.swing.JCheckBox();
        quaTarde = new javax.swing.JCheckBox();
        quiManha = new javax.swing.JCheckBox();
        quiNoite = new javax.swing.JCheckBox();
        quiTarde = new javax.swing.JCheckBox();
        sexManha = new javax.swing.JCheckBox();
        sexNoite = new javax.swing.JCheckBox();
        sexTarde = new javax.swing.JCheckBox();
        sabManha = new javax.swing.JCheckBox();
        sabNoite = new javax.swing.JCheckBox();
        sabTarde = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pronto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Escolha dias e horários em que deseja que o evento ocorra");

        domNoite.setText("Noite");

        domTarde.setText("Tarde");

        domManha.setText("Manhã");

        segManha.setText("Manhã");

        segNoite.setText("Noite");

        segTarde.setText("Tarde");

        terManha.setText("Manhã");

        terNoite.setText("Noite");

        terTarde.setText("Tarde");

        quaManha.setText("Manhã");

        quaNoite.setText("Noite");

        quaTarde.setText("Tarde");

        quiManha.setText("Manhã");

        quiNoite.setText("Noite");

        quiTarde.setText("Tarde");

        sexManha.setText("Manhã");

        sexNoite.setText("Noite");

        sexTarde.setText("Tarde");

        sabManha.setText("Manhã");

        sabNoite.setText("Noite");

        sabTarde.setText("Tarde");

        jLabel3.setText("Domingo");

        jLabel4.setText("Segunda");

        jLabel5.setText("Terça");

        jLabel6.setText("Quarta");

        jLabel7.setText("Quinta");

        jLabel8.setText("Sexta");

        jLabel9.setText("Sábado");

        pronto.setText("Pronto");
        pronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quiManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quiTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quiNoite))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quaManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quaTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quaNoite))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sexManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sexTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexNoite))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sabManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sabTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sabNoite))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(terManha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(terTarde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(terNoite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(segManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(segTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(segNoite))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(domManha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(domTarde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(domNoite)))))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(pronto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domNoite)
                    .addComponent(domTarde)
                    .addComponent(domManha)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segNoite)
                    .addComponent(segTarde)
                    .addComponent(segManha)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terNoite)
                            .addComponent(terTarde)
                            .addComponent(terManha)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quaNoite)
                    .addComponent(quaTarde)
                    .addComponent(quaManha)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiNoite)
                    .addComponent(quiTarde)
                    .addComponent(quiManha)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexNoite)
                    .addComponent(sexTarde)
                    .addComponent(sexManha)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sabManha)
                    .addComponent(sabTarde)
                    .addComponent(sabNoite)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(pronto)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoActionPerformed
        this.dispose();
    }//GEN-LAST:event_prontoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox domManha;
    private javax.swing.JCheckBox domNoite;
    private javax.swing.JCheckBox domTarde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton pronto;
    private javax.swing.JCheckBox quaManha;
    private javax.swing.JCheckBox quaNoite;
    private javax.swing.JCheckBox quaTarde;
    private javax.swing.JCheckBox quiManha;
    private javax.swing.JCheckBox quiNoite;
    private javax.swing.JCheckBox quiTarde;
    private javax.swing.JCheckBox sabManha;
    private javax.swing.JCheckBox sabNoite;
    private javax.swing.JCheckBox sabTarde;
    private javax.swing.JCheckBox segManha;
    private javax.swing.JCheckBox segNoite;
    private javax.swing.JCheckBox segTarde;
    private javax.swing.JCheckBox sexManha;
    private javax.swing.JCheckBox sexNoite;
    private javax.swing.JCheckBox sexTarde;
    private javax.swing.JCheckBox terManha;
    private javax.swing.JCheckBox terNoite;
    private javax.swing.JCheckBox terTarde;
    // End of variables declaration//GEN-END:variables
    
    public boolean getDomManha(){
        return domManha.isSelected();
    }
    
    public boolean getDomTarde(){
        return domTarde.isSelected();
    }
    
    public boolean getDomNoite(){
        return domNoite.isSelected();
    }
    
    public boolean getSegManha(){
        return segManha.isSelected();
    }
    
    public boolean getSegTarde(){
        return segTarde.isSelected();
    }
    
    public boolean getSegNoite(){
        return segNoite.isSelected();
    }
    
    public boolean getTerManha(){
        return terManha.isSelected();
    }
    
    public boolean getTerTarde(){
        return terTarde.isSelected();
    }
    
    public boolean getTerNoite(){
        return terNoite.isSelected();
    }
    
    public boolean getQuaManha(){
        return quaManha.isSelected();
    }
    
    public boolean getQuaTarde(){
        return quaTarde.isSelected();
    }
    
    public boolean getQuaNoite(){
        return quaNoite.isSelected();
    }
    
    public boolean getQuiManha(){
        return quiManha.isSelected();
    }
    
    public boolean getQuiTarde(){
        return quiTarde.isSelected();
    }
    
    public boolean getQuiNoite(){
        return quiNoite.isSelected();
    }
    
    public boolean getSexManha(){
        return sexManha.isSelected();
    }
    
    public boolean getSexTarde(){
        return sexTarde.isSelected();
    }
    
    public boolean getSexNoite(){
        return sexNoite.isSelected();
    }
    
    public boolean getSabManha(){
        return sabManha.isSelected();
    }
    
    public boolean getSabTarde(){
        return sabTarde.isSelected();
    }
    
    public boolean getSabNoite(){
        return sabNoite.isSelected();
    }
}
